CREATE TABLE "colas" (
  "cola_id" bigint PRIMARY KEY,
  "permit_num" varchar,
  "serial_num" varchar,
  "brand_name" varchar,
  "fanciful_name" varchar,
  "origin_code" integer,
  "origin" varchar,
  "class_type_code" integer,
  "class_type" varchar,
  "completed_date" date,
  "scraped_on" datetime,
  "image_count_to_parse" int
);

CREATE TABLE "cola_images" (
  "cola_id" bigint,
  "file_name" varchar,
  "img_type" varchar,
  "width_px" int,
  "height_px" int,
  "dimensions_txt" varchar,
  "local_path" varchar,
  "scraped_on" datetime,
  PRIMARY KEY ("cola_id", "file_name")
);

CREATE TABLE "cola_image_analysis" (
  "cola_id" bigint,
  "file_name" varchar,
  "analysis_model" varchar,
  "model_version" varchar,
  "analysis_completed_on" datetime,
  "metadata" json,
  PRIMARY KEY ("cola_id", "file_name", "analysis_model")
);

CREATE TABLE "image_analysis_items" (
  -- "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cola_id" bigint,
  "file_name" varchar,
  "analysis_model" varchar,
  "analysis_item_type" varchar,
  "text" varchar,
  "model_confidence" float,
  "bounding_box" json
);

COMMENT ON COLUMN "colas"."scraped_on" IS 'the date the cola characteristic data was scraped from the public COLA registry';

COMMENT ON COLUMN "cola_images"."width_px" IS 'the pixel width as represented in the html <img> tag from the public COLA registry';

COMMENT ON COLUMN "cola_images"."height_px" IS 'the pixel height as represented in the html <img> tag from the public COLA registry';

COMMENT ON COLUMN "cola_images"."dimensions_txt" IS 'the dimensions present on the COLA form printout page, presumably entered by the submitter of the label';

COMMENT ON COLUMN "cola_images"."local_path" IS 'the local, relative path of the image file';

COMMENT ON COLUMN "cola_images"."scraped_on" IS 'the date the cola image characteristic data was scraped from the public COLA registry';

COMMENT ON COLUMN "cola_image_analysis"."analysis_model" IS 'the model used to produce the analysis output';

COMMENT ON COLUMN "cola_image_analysis"."model_version" IS 'the version of the analysis model used';

COMMENT ON COLUMN "cola_image_analysis"."analysis_completed_on" IS 'the date the analysis was completed';

COMMENT ON COLUMN "image_analysis_items"."analysis_item_type" IS 'e.g., tag, caption, object, text block, text line, etc.';

-- ALTER TABLE "cola_images" ADD FOREIGN KEY ("cola_id") REFERENCES "colas" ("cola_id");

-- ALTER TABLE "cola_image_analysis" ADD FOREIGN KEY ("cola_id") REFERENCES "cola_images" ("cola_id");

-- ALTER TABLE "cola_image_analysis" ADD FOREIGN KEY ("file_name") REFERENCES "cola_images" ("file_name");

-- ALTER TABLE "image_analysis_items" ADD FOREIGN KEY ("cola_id") REFERENCES "cola_image_analysis" ("cola_id");

-- ALTER TABLE "image_analysis_items" ADD FOREIGN KEY ("file_name") REFERENCES "cola_image_analysis" ("file_name");

-- ALTER TABLE "image_analysis_items" ADD FOREIGN KEY ("analysis_model") REFERENCES "cola_image_analysis" ("analysis_model");
